apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: nestor
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
      env:
      - name: AtgDatabaseProvider__Provider
        value: SqlServer
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: nestor
  labels:
    app: httpd
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: httpd
  type: LoadBalancer
